Flask/website/auth.py
# All of the imports needed for this page to opperate 
from flask import Flask, Blueprint, render_template, request, url_for, redirect, session
from pymongo import MongoClient
from website.views import views
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from flask_pymongo import PyMongo
from website.models import User
from flask_session import Session
# In order to check the date for SOTM for when to refresh the SOTM random winners
from datetime import date
import time
# To authenticate the MognoClient, certifi is required
import certifi
# to get random winners for SOTM
import random
# Our database connection and how it is set up for the authentication later 
ca = certifi.where()
client = MongoClient("mongodb+srv://mrmutturaja389:FBLA202223@fbla.mrh4gqm.mongodb.net/?retryWrites=true&w=majority", tlsCAFile=ca)
db = client.dpfbla
auth = Blueprint('auth', __name__)
s = db.fbladata
c = db.clubs
@auth.route("/SignIn", methods=['GET', 'POST'])
def signin():
    # Signs in user and saves all of their data to a flask session
    data = request.form
    email = data.get('email')
    password = data.get('password')
    if email != None and password != None:
        check = s.find_one({'username': email})
        if check != None:
            if check['password'] == password:
                login_user(User(check), remember=True)
                session["email"] = email
                session["password"] = password
                session["first_name"] = check['first_name']
                session["last_name"] = check['last_name']
                session["grade"] = check['grade']
                session["points"] = check['points']
                session["prizes"] = False
                session["clubs"] = check['clubs']
                session["type"] = check['type']
                session["events"] = None
                high = 0
                listnine = []
                listten = []
                listeleven = []
                listtwelve = []
                if session.get('highestfn') == None:
                    for document in s.find():
                        if document['points'] > high:
                            session["highestfn"] = document['first_name']
                            session["highestln"] = document['last_name']
                            session["highestg"] = document['grade']
                            session["highestp"] = document['points']
                            high = document['points']
                        if int(document['grade']) == 9:
                            listnine.append(document)
                        elif int(document['grade']) == 10:
                            listten.append(document)
                        elif int(document['grade']) == 11:
                            listeleven.append(document)
                        else:
                            listtwelve.append(document)
                    ninesotm = random.choice(listnine)
                    tensotm = random.choice(listten)
                    elevensotm = random.choice(listeleven)
                    twelvesotm = random.choice(listtwelve)
                    session["sotm9fn"] = ninesotm['first_name']
                    session["sotm9ln"] = ninesotm['last_name']
                    session["sotm9p"] = ninesotm['points']
                    session["sotm10fn"] = tensotm['first_name']
                    session["sotm10ln"] = tensotm['last_name']
                    session["sotm10p"] = tensotm['points']
                    session["sotm11fn"] = elevensotm['first_name']
                    session["sotm11ln"] = elevensotm['last_name']
                    session["sotm11p"] = elevensotm['points']
                    session["sotm12fn"] = twelvesotm['first_name']
                    session["sotm12ln"] = twelvesotm['last_name']
                    session["sotm12p"] = twelvesotm['points']
                for club in session["clubs"]:
                    session[club] = c.find_one({'clubname': club})['events']
                if check['type'] == "admin":
                    return redirect(url_for('views.HomeAD'))
                elif check['type'] == "sponsor":
                    return redirect(url_for('views.HomeSP'))
                else:
                    return redirect(url_for('views.HomeST'))
    return render_template("SignIn.html", user=current_user)

@auth.route("/SignUp", methods=['GET', 'POST'])
def signup():
    # Signs up user and redirects them to sign in
    email = request.form.get('email')
    password = request.form.get('password')
    first_name = request.form.get('first_name')
    last_name = request.form.get('last_name')
    points = 0
    
    # Insert new user document into the fbladata collection
    if email != None:
        grade = int(request.form.get('grade'))
        s.insert_one({'username': email, 'password': password, 'first_name': first_name, 'last_name': last_name, 'grade': grade, 'points': points, 'clubs':{}, 'type': "student"})
        check = s.find_one({'username': email})
        login_user(User(check), remember=True)
        return redirect(url_for('auth.signin'))
    # Redirect the user to the home page
    return render_template("SignUp.html", user=current_user)

@auth.route("/logout")
@login_required
def logout():
    # Saves all parts of session that need to be saved and clears every other part of the session while updating the points to MongoDB
    a = session["highestfn"]
    b = session["highestln"]
    c = session["highestg"]
    d = session["highestp"]
    e = session["sotm9fn"]
    f = session["sotm9ln"]
    g = session["sotm9p"]
    h = session["sotm10fn"]
    i = session["sotm10ln"]
    j = session["sotm10p"]
    k = session["sotm11fn"]
    l = session["sotm11ln"]
    m = session["sotm11p"]
    n = session["sotm12fn"]
    o = session["sotm12ln"]
    p = session["sotm12p"]
    s.find_one_and_update({"first_name": session['first_name']}, {"$set": {"points": session['points']}})
    session.clear()
    logout_user()
    session["highestfn"] = a
    session["highestln"] = b
    session["highestg"] = c
    session["highestp"] = d
    session["sotm9fn"] = e
    session["sotm9ln"] = f
    session["sotm9p"] = g
    session["sotm10fn"] = h
    session["sotm10ln"] = i
    session["sotm10p"] = j
    session["sotm11fn"] = k
    session["sotm11ln"] = l
    session["sotm11p"] = m
    session["sotm12fn"] = n
    session["sotm12ln"] = o
    session["sotm12p"] = p
    return redirect(url_for('views.HomeNA'))



@views.route("/NewClub", methods=['GET', 'POST'])
def Club():
    # Adds club to club database
    clubname = request.form.get('clubname')
    sponsorname = request.form.get('sponsorname')
    sponsoremail = request.form.get('sponsoremail')
    roomnum = request.form.get('roomnum')
    
    if clubname != None:
        c.insert_one({'clubname': clubname, 'sponsorname': sponsorname, 'sponsoremail': sponsoremail, 'roomnum': int(roomnum)})
        return redirect(url_for('views.HomeAD'))
    return render_template("NewClub.html", user=current_user)

Flask/website/templates/FAQ.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FAQ</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style3.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
</head>
<body>
<!-- Setting up the Page -->
  <header class="TBanner"></header>
  <div class = "mainhead">LHS Student Involvement Tracker</div>
<!-- If then statements checking if student is logged in -->
  {%if current_user.is_anonymous%}
  <a href="/SignIn"><button class = "Sign">Sign In</button></a>
  <a href = "/"><img src="{{ url_for('static', filename='Logo.png') }}" class="logo"></a>
  {%else%}
  <div class = "name">{{session.first_name}} {{session.last_name}}</div>
  {%if session.type == "admin"%}
  <a href = "/home/Admin"><img src="{{ url_for('static', filename='Logo.png') }}" class="logo"></a>
  {%endif%}
  {%if session.type == "student"%}
  <a href = "/home/Student"><img src="{{ url_for('static', filename='Logo.png') }}" class="logo"></a>
  {%endif%}
  {%if session.type == "sponsor"%}
  <a href = "/home/Sponsor"><img src="{{ url_for('static', filename='Logo.png') }}" class="logo"></a>
  {%endif%}
  {%endif%}
<!-- Setting up Menu button -->
  <div class="dropdown">
    <div class = "hov">
      <div class = "bar one"></div>
      <div class = "bar two"></div>
      <div class = "bar three"></div>
      <div class = "square"></div>
    </div>
    <div class="dropdown-content">
      <a href="/Prizes">Prizes</a>
      <a href="/SOTM">SOTM</a>
      <a href="/quarterly-report">Quarterly Report</a>
      {% if current_user.is_authenticated%}
      <a href="/NewClub">New Club</a>
      <a href="/logout">Sign Out</a>
      {% endif %}
    </div>
  </div>
  <br></br>
  <br></br>
  <br></br>
  <br></br>
  <br></br>
  <br></br>
<!-- Setting up the FAQ page -->
  <div class="container">
      <h1>Frequently Asked Questions</h1>
    <div class="accordion">
        <div class="accordion-item">
            <div class="accordion-header">
                <h3>How do you add points?</h3>
            </div>
            <div class="accordion-content">            </div>
               <h4> Once you are signed into your account, you should see a "+" icon on the bottom right. Click on it and fill it out, then your club/sport advisor will grant you points. If they feel like the amount you requested dosent add up, then they will deny your points.</h4>
        </div>
        <div class="accordion-item">
            <div class="accordion-header">
                <h3>How do you join a club/sport?</h3>
            </div>
            <div class="accordion-content"> </div>
            <h4>Once you are logged in, you have to fill out a form with the clubs and sports that you are in. The advisors of those will check if you are in them and they will grant you permission to join. They can also deny your request if they want to.</h4>
           
        </div>
        <div class="accordion-item">
            <div class="accordion-header">
                <h3>Will my points stack up over the years?</h3>
            </div>
            <div class="accordion-content"></div>
                <h4>Yes, you can stack your points from Freshman year all the way up to the End of Senior Year. Once you graduate, your account will be discontinued. So make sure to spend all your points while you can.</h4>
        </div>
    </div>

Flask/website/templates/HomeAD.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LHS Studnet Involvement Tracker</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
</head>
<body>
<!-- Page Setup -->
  <header class="TBanner"></header>
  <div class = "mainhead">LHS Student Involvement Tracker</div>
  <div class = "name">{{session.first_name}} {{session.last_name}}</div>
  <img src="{{ url_for('static', filename='Logo.png') }}" class="logo">
  <div class = "welcome">Welcome</div>
  <div class = "welcomedescription">Welcome to the LHS Student Involvement Tracker!</div>
<!-- Set up of the 2 buttons in the middle of the page -->
  <a href = "/Sports"><button class = "sports">View Sports</button></a>
  <a href = "/Clubs"><button class = "clubs">View Clubs</button></a>
<!-- Set Up of the menu except now that a person is signed in, they will get all the options -->
  <div class="dropdown">
    <div class = "hov">
      <div class = "bar one"></div>
      <div class = "bar two"></div>
      <div class = "bar three"></div>
      <div class = "square"></div>
    </div>
    <div class="dropdown-content">
      <a href="/Prizes">Prizes</a>
      <a href="/SOTM">SOTM</a>
      <a href="/NewClub">New Club</a>
      <a href="/quarterly-report">Quarterly Report</a>
      <a href="/FAQ">FAQ</a>
      <a id="myBtn">Account</a>
      <a href="/logout">Sign Out</a>
    </div>
  </div>
<!-- Setting up the upcoming events banner -->
  <div class="Mbanner">
    <h1 class = "Mtext1">Upcoming</h1>
    <br><br>
    <h1 class = "Mtext2">Events</h1>
    <div class="line"></div>
    <h1 class="Mevents1">FBLA State</h1>
    <br></br>
    <h1 class = "Mevents2">4/17- 4/19</h1>
    <h1 class="Mevents3">Tennis Tournament</h1>
    <br></br>
    <h1 class = "Mevents4">4/20</h1>
    <h1 class="Mevents5">NHS Meeting</h1>
    <br></br>
    <h1 class = "Mevents6">4/25</h1>
    <h1 class="Mevents7">Track Competition</h1>
    <br></br>
    <h1 class = "Mevents8">4/28</h1>
  </div>
<!-- Set up of the account pop up button -->
  <div class="circlebutton" id="mybutton">+</div>
  <div class="modal-content" id="myModal">
    <div class="modal-header">
      <span class="close" id="closebutton">&times;</span>
      <h2>Welcome {{session.first_name}} {{session.last_name}}</h2>
    </div>
    <div class="modal-body">
      <p>Email: {{session.email}}</p>
      <p>Password: {{session.password}}</p>
      <p>Grade: {{session.grade}}</p>
      <p>Points: {{session.points}}</p>
      <p>Status: {{session.type}}</p>
    </div>
  </div>
<!-- Set up of the points sytem and how to add points -->
  <form class="modal-content" id="formModal" method="POST">
    <div class="modal-header">
      <span class="close" id="closebutton2">&times;</span>
      <h2>Add Points</h2>
    </div>
    <div class="modal-body">
      <br>
      <label for="club">Clubs:</label>
      <select id="club" name="club" required>
        <option value=0>Select Club</option>
        {% for club in session.clubs%}
          <option value={{club}}>{{club}}</option>
        {% endfor %}
      </select>
      <br><br>
      <label for="point">Points:</label>
      <select id="point" name="point" required>
        <option value=0>0</option>
        <option value=1>1</option>
        <option value=2>2</option>
        <option value=3>3</option>
        <option value=4>4</option>
        <option value=5>5</option>
      </select>
      <br><br>
      <label for="point">Add Points:</label>
      <input type = "checkbox" value = "check" name="check" id="check" required>
      <br><br>
      <input type="submit" value="Add" id="subform" required>
      <br><br>
    </div>
  </div>

  <script type="text/javascript" src="{{ url_for('static', filename='modal.js') }}"></script>
</body>
</html>

Flask/website/templates/HomeNA.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LHS Student Involvement Tracker</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
</head>
<body>
<!-- Seetting up the page -->
  <script src="java.js"></script>
  <header class="TBanner"></header>
  <div class = "mainhead">LHS Student Involvement Tracker</div>
  <img src="{{ url_for('static', filename='Logo.png') }}" class="logo">
  <div class = "welcome">Welcome</div>
  <div class = "welcomedescription">Welcome to the LHS Student Involvement Tracker!</div>
<!-- Adding the 3 major buttons -->
  <a href = "/SignIn"><button class = "Sign">Sign In</button></a>
  <a href = "/Sports"><button class = "sports">View Sports</button></a>
  <a href = "/Clubs"><button class = "clubs">View Clubs</button><ul></a>
<!-- Set up of the menu button -->
  <div class="dropdown">
    <div class = "hov">
      <div class = "bar one"></div>
      <div class = "bar two"></div>
      <div class = "bar three"></div>
      <div class = "square"></div>
    </div>
<!-- This page is the main page so these links are always static -->
    <div class="dropdown-content">
      <a href="/Prizes">Prizes</a>
      <a href="/SOTM">SOTM</a>
      <a href="/quarterly-report">Quarterly Report</a>
      <a href="/FAQ">FAQ</a>
    </div>
  </div>
<!-- Set up of the middle banner -->
  <div class="Mbanner">
    <h1 class = "Mtext1">Upcoming</h1>
    <br><br>
    <h1 class = "Mtext2">Events</h1>
    <div class="line"></div>
    <h1 class="Mevents1">FBLA State</h1>
    <br></br>
    <h1 class = "Mevents2">4/17- 4/19</h1>
    <h1 class="Mevents3">Tennis Tournament</h1>
    <br></br>
    <h1 class = "Mevents4">4/20</h1>
    <h1 class="Mevents5">NHS Meeting</h1>
    <br></br>
    <h1 class = "Mevents6">4/25</h1>
    <h1 class="Mevents7">Track Competition</h1>
    <br></br>
    <h1 class = "Mevents8">4/28</h1>


  </div>
<body>
</html>

Flask/website/templates/HomeSP.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LHS Studnet Involvement Tracker</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
</head>
<body>
<!-- Page Setup -->
  <header class="TBanner"></header>
  <div class = "mainhead">LHS Student Involvement Tracker</div>
  <div class = "name">{{session.first_name}} {{session.last_name}}</div>
  <img src="{{ url_for('static', filename='Logo.png') }}" class="logo">
  <div class = "welcome">Welcome</div>
  <div class = "welcomedescription">Welcome to the LHS Student Involvement Tracker!</div>
<!-- Set up of the 2 major buttons -->
  <a href = "/Sports"><button class = "sports">View Sports</button></a>
  <a href = "/Clubs"><button class = "clubs">View Clubs</button></a>
<!-- Setup of the menmu button -->
  <div class="dropdown">
    <div class = "hov">
      <div class = "bar one"></div>
      <div class = "bar two"></div>
      <div class = "bar three"></div>
      <div class = "square"></div>
    </div>
<!-- This page is for people signed in so they will have all options possible -->
    <div class="dropdown-content">
      <a href="/Prizes">Prizes</a>
      <a href="/SOTM">SOTM</a>
      <a href="/NewClub">New Club</a>
      <a href="/quarterly-report">Quarterly Report</a>
      <a href="/FAQ">FAQ</a>
      <a id="myBtn">Account</a>
      <a href="/logout">Sign Out</a>
    </div>
  </div>
<!-- setup of the middle banner -->
  <div class="Mbanner">
    <h1 class = "Mtext1">Upcoming</h1>
    <br><br>
    <h1 class = "Mtext2">Events</h1>
    <div class="line"></div>
    <h1 class="Mevents1">FBLA State</h1>
    <br></br>
    <h1 class = "Mevents2">4/17- 4/19</h1>
    <h1 class="Mevents3">Tennis Tournament</h1>
    <br></br>
    <h1 class = "Mevents4">4/20</h1>
    <h1 class="Mevents5">NHS Meeting</h1>
    <br></br>
    <h1 class = "Mevents6">4/25</h1>
    <h1 class="Mevents7">Track Competition</h1>
    <br></br>
    <h1 class = "Mevents8">4/28</h1>
  </div>
<!-- Setup of the account popup button -->
  <div class="circlebutton" id="mybutton">+</div>
  <div class="modal-content" id="myModal">
    <div class="modal-header">
      <span class="close" id="closebutton">&times;</span>
      <h2>Welcome {{session.first_name}} {{session.last_name}}</h2>
    </div>
    <div class="modal-body">
      <p>Email: {{session.email}}</p>
      <p>Password: {{session.password}}</p>
      <p>Grade: {{session.grade}}</p>
      <p>Points: {{session.points}}</p>
      <p>Status: {{session.type}}</p>
    </div>
  </div>
<!-- Setup of how to add points and your balence -->
  <form class="modal-content" id="formModal" method="POST">
    <div class="modal-header">
      <span class="close" id="closebutton2">&times;</span>
      <h2>Add Points</h2>
    </div>
    <div class="modal-body">
      <br>
      <label for="club">Clubs:</label>
      <select id="club" name="club" required>
        <option value=0>Select Club</option>
        {% for club in session.clubs%}
          <option value={{club}}>{{club}}</option>
        {% endfor %}
      </select>
      <br><br>
      <label for="point">Points:</label>
      <select id="point" name="point" required>
        <option value=0>0</option>
        <option value=1>1</option>
        <option value=2>2</option>
        <option value=3>3</option>
        <option value=4>4</option>
        <option value=5>5</option>
      </select>
      <br><br>
      <label for="point">Add Points:</label>
      <input type = "checkbox" value = "check" name="check" id="check" required>
      <br><br>
      <input type="submit" value="Add" id="subform" required>
      <br><br>
    </div>
  </div>

  <script type="text/javascript" src="{{ url_for('static', filename='modal.js') }}"></script>
</body>
</html>

Flask/website/templates/HomeST.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LHS Studnet Involvement Tracker</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
</head>
<body>
<!-- Page setup -->
  <header class="TBanner"></header>
  <div class = "mainhead">LHS Student Involvement Tracker</div>
  <div class = "name">{{session.first_name}} {{session.last_name}}</div>
  <img src="{{ url_for('static', filename='Logo.png') }}" class="logo">
  <div class = "welcome">Welcome</div>
  <div class = "welcomedescription">Welcome to the LHS Student Involvement Tracker!</div>
<!-- Set up of the 2 major buttons -->
  <a href = "/Sports"><button class = "sports">View Sports</button></a>
  <a href = "/Clubs"><button class = "clubs">View Clubs</button></a>
<!-- Set up of the Menu -->
  <div class="dropdown">
    <div class = "hov">
      <div class = "bar one"></div>
      <div class = "bar two"></div>
      <div class = "bar three"></div>
      <div class = "square"></div>
    </div>
<!-- This person is logged in and will always have all these options -->
    <div class="dropdown-content">
      <a href="/Prizes">Prizes</a>
      <a href="/SOTM">SOTM</a>
      <a href="/NewClub">New Club</a>
      <a href="/quarterly-report">Quarterly Report</a>
      <a href="/FAQ">FAQ</a>
      <a id="myBtn">Account</a>
      <a href="/logout">Sign Out</a>
    </div>
  </div>
<!-- Setup of the middle banner -->
  <div class="Mbanner">
    <h1 class = "Mtext1">Upcoming</h1>
    <br><br>
    <h1 class = "Mtext2">Events</h1>
    <div class="line"></div>
    <h1 class="Mevents1">FBLA State</h1>
    <br></br>
    <h1 class = "Mevents2">4/17- 4/19</h1>
    <h1 class="Mevents3">Tennis Tournament</h1>
    <br></br>
    <h1 class = "Mevents4">4/20</h1>
    <h1 class="Mevents5">NHS Meeting</h1>
    <br></br>
    <h1 class = "Mevents6">4/25</h1>
    <h1 class="Mevents7">Track Competition</h1>
    <br></br>
    <h1 class = "Mevents8">4/28</h1>
  </div>
<!-- Setup of the account pop up option -->
  <div class="circlebutton" id="mybutton">+</div>
  <div class="modal-content" id="myModal">
    <div class="modal-header">
      <span class="close" id="closebutton">&times;</span>
      <h2>Welcome {{session.first_name}} {{session.last_name}}</h2>
    </div>
    <div class="modal-body">
      <p>Email: {{session.email}}</p>
      <p>Password: {{session.password}}</p>
      <p>Grade: {{session.grade}}</p>
      <p>Points: {{session.points}}</p>
      <p>Status: {{session.type}}</p>
    </div>
  </div>
<!-- Setup of the ioption to add points to an account -->
  <form class="modal-content" id="formModal" method="POST">
    <div class="modal-header">
      <span class="close" id="closebutton2">&times;</span>
      <h2>Add Points</h2>
    </div>
    <div class="modal-body">
      <br>
      <label for="club">Clubs:</label>
      <select id="club" name="club" required>
        <option value=0>Select Club</option>
        {% for club in session.clubs%}
          <option value={{club}}>{{club}}</option>
        {% endfor %}
      </select>
      <br><br>
      <label for="point">Points:</label>
      <select id="point" name="point" required>
        <option value=0>0</option>
        <option value=1>1</option>
        <option value=2>2</option>
        <option value=3>3</option>
        <option value=4>4</option>
        <option value=5>5</option>
      </select>
      <br><br>
      <label for="point">Add Points:</label>
      <input type = "checkbox" value = "check" name="check" id="check" required>
      <br><br>
      <input type="submit" value="Add" id="subform" required>
      <br><br>
    </div>
  </div>

  <script type="text/javascript" src="{{ url_for('static', filename='modal.js') }}"></script>
</body>
</html>

Flask/website/templates/NewClub.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='style2.css') }}">
  <title>New Club</title>
</head>
<body>
<!-- Page Setup -->
  <div class="container">
    <header class="TBanner"></header>
<!-- If then statements checking if student is logged in -->
    {%if current_user.is_anonymous%}
    <a href="/SignIn"><button class = "Sign">Sign In</button></a>
    <a href = "/"><img src="{{ url_for('static', filename='Logo.png') }}" class="logo"></a>
    {%else%}
    <div class = "name">{{session.first_name}} {{session.last_name}}</div>
    {%if session.type == "admin"%}
    <a href = "/home/Admin"><img src="{{ url_for('static', filename='Logo.png') }}" class="logo"></a>
    {%endif%}
    {%if session.type == "student"%}
    <a href = "/home/Student"><img src="{{ url_for('static', filename='Logo.png') }}" class="logo"></a>
    {%endif%}
    {%if session.type == "sponsor"%}
    <a href = "/home/Sponsor"><img src="{{ url_for('static', filename='Logo.png') }}" class="logo"></a>
    {%endif%}
    {%endif%}
<!-- Menu Setup -->
    <div class="dropdown">
      <div class = "hov">
        <div class = "bar one"></div>
        <div class = "bar two"></div>
        <div class = "bar three"></div>
        <div class = "square"></div>
      </div>
    <div class="dropdown-content">
      <a href="/Prizes">Prizes</a>
      <a href="/SOTM">SOTM</a>
      <a href="/quarterly-report">Quarterly Report</a>
      <a href="/FAQ">FAQ</a>
    </div>
    </div>
    <div class = "name">{{session.first_name}} {{session.last_name}}</div>
    <div class = "mainhead">LHS Student Involvement Tracker</div>
    <br><br>
    <br><br>
    <br><br>
    <br><br>
<!-- Code for the new club application form -->
    <form method = "POST">
      <h2>New Club Application</h2>
      <label for="username">Name of Club:</label>
      <input type="text" id="clubname" name="clubname" required>
      <br>
      <br>
      <label for="username">Name of Sponsor (First and Last) :</label>
      <input type="text" id="sponsorname" name="sponsorname" required>
      <br>
      <br>
      <label for="username">Sponsor Email:</label>
      <input type="text" id="sponsoremail" name="sponsoremail" required>
      <br>
      <br>
      <label for="username">Room Number for Meetings:</label>
      <input type="text" id="roomnum" name="roomnum" required>
      <br>
      <br>
      <br>
      <input type="submit" value="Submit">
      <br>
      <br>
    </form> 
  </div>

Flask/website/templates/SignIn.html
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="{{ url_for('static', filename='style2.css') }}">
  <link href="https://fonts.googleapis.com/css?family=Comfortaa&display=swap" rel="stylesheet">
  <title>Sign  In</title>
</head>
<body>
<!-- Page Setup -->
  <header class="TBanner"></header>
  <a href = "/"><img src="{{ url_for('static', filename='Logo.png') }}" class="logo"></a>
  <div class = "mainhead">LHS Student Involvement Tracker</div>
  <div class="container">
    <br><br>
    <br><br>
    <br><br>
    <br><br>
    <br><br>
    <br><br>
<!-- Menu Setup -->
    <div class="dropdown">
      <div class = "hov">
        <div class = "bar one"></div>
        <div class = "bar two"></div>
        <div class = "bar three"></div>
        <div class = "square"></div>
      </div>
      <div class="dropdown-content">
        <a href="/Prizes">Prizes</a>
        <a href="/SOTM">SOTM</a>
        <a href="/quarterly-report">Quarterly Report</a>
        <a href="/FAQ">FAQ</a>
      </div>
    </div>
<!-- Form setup for signing in -->
    <form method="POST">
      <h2>Sign In</h2>
      <br>
      <label for="email">Email:</label>
      <input type="text" id="email" name="email">
      <br>
      <br>
      <label for="password">Password:</label>
      <input type="password" id="password" name="password">
      <br><br><br>
      <input type="submit" value="Login">
      <br><br>
<!-- Link for a person without and account -->
      <p>Don't have an account? <a href="{{url_for('auth.signup')}}" class="signup-link">Sign up</a></p>
    </form>
  </div>
</body>
</html>